### ISSUE TITLE
Color-fill not working after resize

### ISSUE THREAD

**Issue by pavsoldatov** [bscottnz/esketch#1]
Not sure, if I'm the first one to notice, but decided to write-in.

Basically, if you resize the grid to any value, the color fill will not work (see the gif). If you resize back to default it will not work too. But it will work as intended when the page is initially loaded.

I might try to fix it, if you give me the green light. My feeling is that the matrix construction is the culprit.

![Retro-Sketch - Google Chrome 2023-01-29 15-42-00](https://user-images.githubusercontent.com/80415302/215330296-4a4496af-2329-4df4-9f51-f3f20f777db0.gif)

**Comment by bscottnz** [comment]
Hey Pavel, good find. I have not come across this before. If you'd like to come up with a fix go ahead, I'd be happy to merge it in 😃

Thanks for letting me know.

**Comment by pavsoldatov** [comment]
Apologies for the delay, I finally sent a PR yesterday.
Just checking-in to make sure you saw it. 😃

https://github.com/bscottnz/esketch/pull/2

**Comment by bscottnz** [comment]
Looks great, thank you very much
